### ISSUE TITLE
HDD doesn't exist at all

### ISSUE THREAD

**Issue by LoganDark** [RamiLego4Game/CC12#1]
`HDD` does not exist!
![image](https://user-images.githubusercontent.com/4723091/31668027-e43d5672-b305-11e7-8d3d-c0c338e55a24.png)
![image](https://user-images.githubusercontent.com/4723091/31668030-ea2fc3bc-b305-11e7-9a69-6eef1b128f9a.png)

**Comment by Rami-Sabbagh** [comment]
The HDD peripheral is available as 'fs' in DiskOS, you can see how that happens in C:/boot.lua.

Note: The HDD/FS API is not available to the games.

**Comment by Rami-Sabbagh** [comment]
Another thing, Yay you found the CC12 project :P, To install CraftOS replace the C drive with allthe files of that repo, and start with boot.lua

**Comment by Rami-Sabbagh** [comment]
Btw, why did you leave the Discord Server ?

**Comment by Rami-Sabbagh** [comment]
Btw, why did you leave the Fantasy Consoles Server ?

**Comment by LoganDark** [comment]
I didn't

**Comment by LoganDark** [comment]
Okay, thanks

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/31743191-14289e5a-b40f-11e7-9197-d31328cc3987.png)

**Comment by LoganDark** [comment]
kernel.lua runs on boot, and also runs bios.lua automatically, and yeah it works
